### ISSUE TITLE
Is there any button names database to use with this?

### ISSUE THREAD

**Issue by RodrigoCard** [cxong/SDL_JoystickButtonNames#1]
like this one for the game controllers:
https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt

**Comment by cxong** [comment]
Yes, this is what this library is supposed to do. See https://github.com/cxong/SDL_JoystickButtonNames/blob/master/gamecontrollerbuttondb.txt

**Comment by RodrigoCard** [comment]
Oh, I did not express myself very well.
I meant something crowd-sourced with more data, the provided one is pretty barebones :)

Did you know if there is someone using this lib? It think it is a pretty good idea and I am surprised there were nothing like this before.

**Comment by cxong** [comment]
Yes! If you own a different controller and have some time, please try out the test app (instructions in readme), and I can add it to the database. See https://github.com/cxong/SDL_JoystickButtonNames/blob/master/README.md#running-the-examples

It's very bare bones because very few people know about this library. I only own two different controllers so that's all that exists so far 😄
